ci: 💚 fix workflow (#2)
* ci: 💚 fix pnpm not found

Fix https://github.com/quadratz/tgast/actions/runs/16293130058/job/46007710153

Error: Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
Signed-off-by: qz <quadratz@proton.me>

* ci: 💚 run `pnpm publish` with `--no-git-checks`

Fix https://github.com/quadratz/tgast/actions/runs/16293263884/job/46008152235:

```log
ERR_PNPM_GIT_UNKNOWN_BRANCH  The Git HEAD may not attached to any branch, but your "publish-branch" is set to "master|main".

If you want to disable Git checks on publish, set the "git-checks" setting to "false", or run again with "--no-git-checks".
 ELIFECYCLE  Command failed with exit code 1.
```

Signed-off-by: qz <quadratz@proton.me>

* ci: 💚 Set up pnpm before publishing to JSR

Fix https://github.com/quadratz/tgast/actions/runs/16293263884/job/46008152249:

```error
/home/runner/work/_temp/28b300ff-ce97-457f-a6af-e17ff205bc8b.sh: line 1: pnpm: command not found
```

Signed-off-by: qz <quadratz@proton.me>

* ci: 💚 use proper caching

Include `node_modules` in the cache. JSR stores their downloaded binaries in their `node_modules`, which can be quite large, around 40 MB. By saving this cache, we hope to reduce both time and resource usage.

Signed-off-by: qz <quadratz@proton.me>

---------

Signed-off-by: qz <quadratz@proton.me>